### ISSUE TITLE
include some QC to avoid permuting region labels

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg#137]
i'm not sure we did.
but also not sure we didn't!

and i'm certainly not sure what to do about it.
but i am sure that we "should" check for the current release, 
and then once we do, build that in somehow?

one simple idea:

plot the degree sequence, ordered by vertex.  
and compare with a previous version of the data (eg, migraine).

that might do it?

**Comment by gkiar** [comment]
Donezo and integrated into graph qc now instead of degree distribution.

Note: currently I am plotting the degree sequence as opposed to the triple-colour sequence we looked at yesterday as it looked overly crowded in small panels. Aso adding a mean-connectome to this plot, we can see if the circshift artifact is present fairly easily. An example plot is shown below.

![screen shot 2017-01-27 at 1 18 23 pm](https://cloud.githubusercontent.com/assets/4883288/22382301/206b5208-e493-11e6-8348-aaef74645d35.png)
