### ISSUE TITLE
np.where best practices

### ISSUE THREAD

**Issue by willgray** [neurodata/ndmg#26]
Confirm we are using np.where the pep8 way. 

Upstream we set a mask equal to True/False, so (np.where == True) should be ok.

PEP8 complains, but may be the parser or still the right way to do it.

**Comment by gkiar** [comment]
When I switched `True` in that statement to `1` the parser stopped
complaining and it still worked. The only risk here is that a mask may
contain values `{0, 100}` or something else arbitrarily not zero or 1.
Perhaps we simply say `>0` instead of `is True` or `== 1` to be robust and
pep8 compliant?

--
Greg Kiar <gkiar07@gmail.com>

**Comment by willgray** [comment]
i believe we addressed this.  It works and is pep8 compliant.
