### ISSUE TITLE
create nifti type converter

### ISSUE THREAD

**Issue by gkiar** [neurodata/ndmg#55]
MRI images are acquired in uint16 with intensities spanning the entire dynamic range. We should develop functionality to quickly normalize all nifti volumes to match this. Because of noise peaks potentially causing distortion, current hypothesis is that we should normalize the values based on the 0th and 95th percentiles, being lower and upper bounds, respectively.

@jovo  @willgray

**Comment by willgray** [comment]
in the priority stack this is after finishing the graphs for sure.  :) 

I want us to do some experiments to understand the choice of different percentiles.  In particular, the current range for our datasets is much different than values I would have expected - for example, the existing float values come nowhere near the max possible value.  Thoughts on that?

The goal for this issue is to determine a normalization scheme in uint16 and stop.  I'm treating the actual upload as a separate activity - I'd prefer to wait on the nd integration until we have the core paper results together.  Discussion welcome.

**Comment by gkiar** [comment]
I agree on all fronts.

--
Greg Kiar <gkiar07@gmail.com>

**Comment by willgray** [comment]
add capability to read and write nifti files with ndio - basic capabilities now exist but basically ignore headers and may not accomodate what's needed to get data from DB.  Also think about what metadata we want to store and how we are storing it for both dti and atlases.

**Comment by gkiar** [comment]
OBE? Randal seemed to want to revive the true nifti service for MR

**Comment by willgray** [comment]
Proceed as planned - we will continue to coordinate with backend as we go

**Comment by gkiar** [comment]
I have made scripts over the last month or so with other deliverables in mind which convert nifti images to either pngs for ndstore ingest or binary files for flashgraph. We can now ingest MR images into ndstore using autoingest, thanks to @Aeusman and @kunallillaney 😄

**Comment by jovo** [comment]
:couples_with_heart:
!!!!

On Fri, Jul 8, 2016 at 10:03 AM, Greg Kiar <notifications@github.com> wrote:

> I have made scripts over the last month or so with other deliverables in
> mind which convert nifti images to either pngs for ndstore ingest or binary
> files for flashgraph. We can now ingest MR images into ndstore using
> autoingest, thanks to @Aeusman <https://github.com/Aeusman> and
> @kunallillaney <https://github.com/kunallillaney> 😄
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndmg/issues/55#issuecomment-231367549>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AACjcv6JUi8CRYQWQy84Bay3TDY2txwtks5qTliagaJpZM4HdYqy>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
