### ISSUE TITLE
Document and discuss ndstore services needed for MRI data

### ISSUE THREAD

**Issue by wrgr** [neurodata/ndmg#61]
@randalburns @kunallillaney @gkiar @jovo

**Comment by willgray** [comment]
For discussion in person:  
- [ ] Propose punting on nifti service because of ndio+nibabel+inconsistent formatting needs
- [ ] Need swc support (RESTful endpoint + RAMONROI + RAMONSkeleton + RAMONNode)
- [ ] float32 datatype outside of [0-1] (maybe not needed)
- [ ] discussion on where to store atlas labels, covariates, and headers (lims or kv pairs?)
