### ISSUE TITLE
be able to pull HCP data directly from their S3 bucket

### ISSUE THREAD

**Issue by jovo** [neurodata/ndmg#89]
i spoke with dan marcus today, he says if @gkiar can pull data directly from HCP bucket and process, that is the ideal scenario.
maybe let's work on that after you get back from stanford?

**Comment by gkiar** [comment]
In a single command? Shouldn't be a problem. I've currently written a few
separate scripts to do these pieces but have them all disjoint atm. Can
pull together in a few days, I bet.

The one lingering issue is that HCP processing is "different" from other
data (as @wrgr has investigated) due to multishell. We'd need multishell
processing code baked in as well in order for me to feel happy/confident in
the HCP connectomes we give people. Estimate for that, likely a week of
playing (less if after the HCP course at the end of August)

--
Greg Kiar <gkiar07@gmail.com>

**Comment by jovo** [comment]
@gkiar not necessarily a single command.
i guess a first step would be a jupyter notebook that gets data and runs our existing pipeline?
then we could integrate @wrgr fancier features as a next step?

**Comment by wrgr** [comment]
m2g tagup 8/9 once the ndpaper is in better shape and @gkiar is back?

**Comment by jovo** [comment]
put in calendar? can we do monday 8am during enhance meeting?

**Comment by wrgr** [comment]
Will do.  Greg is out next week and I'm out the week following.  We can push to 8/15 if that gruntles you more.

**Comment by jovo** [comment]
8/15 is pretty gruntling, though is close to the workshop
@gkiar when is your workshop?

**Comment by gkiar** [comment]
8/28-9/1 I believe. (adding to nd calendar now)

--
Greg Kiar <gkiar07@gmail.com>

On Tue, Jul 26, 2016 at 9:44 AM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
http://www.humanconnectome.org/courses/2016/exploring-the-human-connectome.php
yah

**Comment by wrgr** [comment]
Greg knows this already.  :)  But I'll be in boston for the workshop too!  Will be a blast.

**Comment by gkiar** [comment]
obe -- we have code that pulls any bids organized data from an s3 bucket instead
